name: basic

on: [push, pull_request]

jobs:
  basic:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: False
      matrix:
        python:
          - 2.7.13
          - 3.6.8
        command:
          - pytest
          - ./runPylint.sh
          - |
            if [[ "${REFERENCE_BRANCH}" != "" ]]; then
                git remote add upstream https://github.com/DIRACGrid/DIRAC.git
                git fetch --no-tags upstream "${REFERENCE_BRANCH}"
                git branch -vv
                git diff -U0 "upstream/${REFERENCE_BRANCH}" | pycodestyle --diff
            fi


    steps:
    - uses: actions/checkout@v2
    - name: prepare environment
      run: |
        conda config --set add_pip_as_python_dependency false
        conda create -c conda-forge -c free -n python_${{ matrix.python }} python=${{ matrix.python }}
        source "${CONDA}/bin/activate"
        conda activate python_${{ matrix.python }}
        conda install pytest pylint
    - name: tests
      run: |
        source "${CONDA}/bin/activate"
        conda activate python_${{ matrix.python }}
        set -euxo pipefail
        export PYTHONPATH=${PWD%/*}
        ${{ matrix.command }}
      env:
        REFERENCE_BRANCH: ${{ github['base_ref'] || github['head_ref'] }}
