name: CI

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        python_version:
          - 2.7.13
          - 3.6.8
          - 3.7
          - 3.8
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: .github/workflows/prepare_environment.sh ${{ matrix.python_version }}
    - name: Run pytest
      run: |
        . "${CONDA}/bin/activate" test-env
        pwd
        ls
        ls *
        pytest

  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: .github/workflows/prepare_environment.sh 3
    - name: Run pylint
      run: |
        . "${CONDA}/bin/activate" test-env
        pylint -E diraccfg/ tests/

  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: .github/workflows/prepare_environment.sh 3
    - name: Run pycodestyle
      run: |
        . "${CONDA}/bin/activate" test-env
        pycodestyle

  publish-pypi:
    runs-on: ubuntu-latest
    name: Publish package to PyPI
    needs: [pytest, pylint, pycodestyle]
    steps:
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          repository_url: https://test.pypi.org/legacy/
